### ISSUE TITLE
Bug v3.10.1 - when source puml file not found it does not continue with next item in base_dir

### ISSUE THREAD

**Issue by davama** [mikitex70/plantuml-markdown#102]
Good Day,

Thank you for your work on `v3.10.1`!

Notice a little bug.

When I introduce a new path into `base_dir` which does not contain a source file, it does not want to continue to search on the next path.

```
base_dir:
  - .
  - temp_dir/repos/docker/openldap-symas/docs
  - temp_dir/repos/docker/redis/docs
```

The source file is located in `redis/docs` but stops at `openldap-symas/docs` with this output:
![2024-08-08_11-52](https://github.com/user-attachments/assets/80458f95-e134-4636-92e1-922bcde49373)

If I flip the order I have no issue.

```
  - temp_dir/repos/docker/redis/docs
  - temp_dir/repos/docker/openldap-symas/docs
```

Thank you again for your assistance!

Best,
Dave

**Comment by mikitex70** [comment]
Ho @davama, I've fixed the bug.
Sorry for the stupid error ...
