### ISSUE TITLE
Getting this working in a windows context

### ISSUE THREAD

**Issue by Analect** [mikitex70/plantuml-markdown#11]
@mikitex70 
I've been trying to get this working on windows 7, but am somehow stuck.  Perhaps you may have some pointers.

The jar file is located here: `c:\plantuml\plantuml.jar`

I have created a bash file and saved it as `c:\plantuml\plantuml.sh`

```
#!/bin/bash
java -jar c:\\plantuml\\plantuml.jar ${@}
```
I'm running mkdocs in a conda environment called 'client-docs', so have copied `plantuml.py` to `c:\Users\xxxx\AppData\Local\Continuum\Miniconda3\envs\client-docs\Lib\site-packages\markdown\extensions\plantuml.py`.

In order to call the bash file above with a single `plantuml` command, I have set an alias using doskey:

`doskey plantuml=bash "c:\plantuml\plantuml.sh"`

In the mkdocs.yml, I have:
```
markdown_extensions:
  - plantuml
```
However, when I try to run `mkdocs serve -a 0.0.0.0:8000`, I get an exception from the plantuml.py above:

```
... plantuml.py, line 166, in generate_uml_image
raise Exception('Failed to run plantuml: %s' % exc)
Exception: Failed to run plantuml: [WinError 2] The system cannot find the file specified
```
Any thoughts on what I might be doing wrong here?  Thanks

**Comment by mikitex70** [comment]
I don't have a Windows machine to test, bu try this `plantuml.bat`:

```bat
"C:\Program Files\Java\java" -jar plantuml.jar %1 %2 %3 %4
```
Check where is the `java.exe` in your system and adjust the path in the above script.
Place the `plantuml.jar` in the same folder of the `plantuml.bat`.
Then add then path where you placed the `plantuml.bat` to the system path (search in Internet how to change the `PATH` variable in Windows).
Or, for a quick test, copy the `plantuml.bat` and `plantuml.jar` in `C:\Windows`; it's a bit dirty but for testing may be done.
To test if the installation is working, simply try the command `plantuml`, without arguments and it should open a dialog.

**Comment by Analect** [comment]
Thanks @mikitex70  ... I think that probably works ... except I'm hitting this other problem in running plantuml related to java.  It seems to be a know issue [here](https://stackoverflow.com/questions/5354838/java-java-util-preferences-failing) and [here](https://stackoverflow.com/questions/16428098/groovy-shell-warning-could-not-open-create-prefs-root-node).  However, I lack Admin priveleges on this work machine so am a bit stuck. Frustrating.

**Comment by mikitex70** [comment]
Hi @henn1001, thanks for your suggestions.
I've commited the version `1.2.5`, that can now be installed with a simple `pip install plantuml-markdown`. In this version I've added a workaround to let Windows find and run the batch file.
I've added a test for the operating system because using `shell=True` for some reason will broke automated tests under Linux (plantuml will open a dialog).
I hope the workaround will work fine.
Thanks again for your Windows batch file, it is now mentioned in the documentation.

**Comment by vstriz** [comment]
When will 1.2.5 be available on "pip install" ? I'm only able to get 1.2.4 and I need the above fix.

Thanks a lot.

**Comment by mikitex70** [comment]
Hi @vstriz, sorry for the mistake: I've uploaded only the package for Python 3.
It's my first release and I still learning.
But now I've uploaded also the package for Python 2.7, so try again with `pip`.

**Comment by vstriz** [comment]
Thank you @mikitex70 for answering. I was really hoping it would work but it still doesn't seem to find it.  I'm a little beyond my depth here to figure out why though. AFAICT it still doesn't find python-2.7 package for version 1.2.5 with pip

**Comment by vstriz** [comment]
You can check on pypi.org available packages:

https://pypi.org/project/plantuml-markdown/1.2.5/#files

vs.

https://pypi.org/project/plantuml-markdown/1.2.4/#files


You will see that 1.2.5 still doesn't have "py2" package

**Comment by mikitex70** [comment]
Ok, now there is also a 1.2.5 package for Python 2.7.
I hope now is all ok.
