### ISSUE TITLE
svg_inline

### ISSUE THREAD

**Issue by karlssonjohan** [mikitex70/plantuml-markdown#18]
Hi, maybe this is more of a support question I think.... anyway, I tried the svg_inline option but the a link in the diagram is not clickable. Do I need to add CSS to make it clickable? I am using Firefox 63.

**Comment by mikitex70** [comment]
The problem was related to the namespaces for links: it seems that it must be `xmlns:xlink` to be recognized by the browsers so they can activate the hyperlinks.
Now is fixed, use the `1.4.0` version.
