### ISSUE TITLE
I can't import the extension after the rename to "plantuml-markdown"

### ISSUE THREAD

**Issue by hjalves** [mikitex70/plantuml-markdown#23]
I can't use the extension with the new name. 

Error in the shell:

```
In [3]: import plantuml-markdown                                                                                                                                                                                               
  File "<ipython-input-3-116cbb124db8>", line 1
    import plantuml-markdown
                   ^
SyntaxError: invalid syntax
```

Error in `mkdocs serve`:

```
INFO    -  Building documentation... 
ERROR   -  Config value: 'markdown_extensions'. Error: Failed loading extension "plantuml-markdown". 

Aborted with 1 Configuration Errors!
```

Am I missing something? I'm feeling a bit dumb.
Thank you

**Comment by mikitex70** [comment]
You are right, my mistake: I need to rename the file to `plantuml_markdown.py` to be able to import it.
Another change that would broken current usages... I have to be more careful in development.
I would try to make a new release this weekend.

**Comment by mikitex70** [comment]
But with `mkdocs` it should work: my `mkdocs.yml` is like:
```yaml
markdown_extensions:
    - plantuml-markdown:
        server: http://www.plantuml.com/plantuml
```
I'm using `mkdocs:1.0.4`

**Comment by mikitex70** [comment]
Module renamed.
Plugin configuration in `markdown_py` must be changed too.
Thanks for pointing out to me this mistake.
