### ISSUE TITLE
Gantt diagram fails to render

### ISSUE THREAD

**Issue by vesakivisto** [mikitex70/plantuml-markdown#25]
I'm trying to render a gantt diagram using MkDocs with plantuml-markdown extension at GitLab. The diagram renders succesfully on the .md file that contains the syntax, but it fails to render on GitLab pages which I create with MkDocs. It instead renders an image underscoring a line in the used syntax with "Syntax error?" text under it.

The syntax used is as follows:
````
```plantuml
[Prototype design] lasts 15 days
[Test prototype] lasts 10 days
```
````

Am I missing something here?

**Comment by mikitex70** [comment]
Maybe the `plantuml.jar` used is not recent enough: gantt diagrams are a recent introduction in plantuml.
I don't know how pages are rendered in GitLab, but maybe they are using a different plugin, or maybe an old version of my plugin.
Latest release of this plugin can use the [plantuml server](http://www.plantuml.com/plantuml) for rendering diagrams, and thus it always uses the latest jar version.
A solution is to upload pre-rendered diagrams, but it isn't a real solution and producing documentation becomes a little tricky.

**Comment by vesakivisto** [comment]
Apparently adding the PlantUML server definition under plantuml_markdown to my mkdocs.yml fixed this issue. I guess MkDocs can't use the PlantUML server specified in GitLad configuration and it needs the definition in the mkdocs.yml.

**Comment by mikitex70** [comment]
It seems that GitLab uses a local version on PlantUML, too old to be able to render Gantt diagrams.
Configuring the server remote url with the [plantuml server](http://www.plantuml.com/plantuml) url you are sure to always use the latest available version of PlantUML.
I close this issue as is not related to this plugin, and there is a simple workaround to the problem.
Thanks for your report, maybe it can be useful to others.
