### ISSUE TITLE
3.1.1 contains invalid `plantuml.py` file

### ISSUE THREAD

**Issue by nshmura** [mikitex70/plantuml-markdown#30]
Since plantuml_markdown-3.1.1 contains invalid `plantuml.py` file, it seems breaks site-packages of python.

Both `plantuml_markdown-3.1.1-py2-none-any.whl` and `plantuml_markdown-3.1.1-py3-none-any.whl`  cointains following files
```
plantuml.py
plantuml_markdown.py
plantuml_markdown-3.1.1.dist-info
```
see: https://pypi.org/project/plantuml-markdown/3.1.1/#files

Will you please remove plantuml.py from whl?

**Comment by mikitex70** [comment]
My fault, I didn't clean the directory before creating the packages...
Sorry.

**Comment by mikitex70** [comment]
Thanks for reporting this issue.
Try the 3.1.2 version, now it should be ok.

**Comment by nshmura** [comment]
@mikitex70

**Comment by nshmura** [comment]
@mikitex Thank you for your quick fix!
