### ISSUE TITLE
'/' in 'alt' or 'title' prevents diagram from rendering

### ISSUE THREAD

**Issue by jean** [mikitex70/plantuml-markdown#36]
This diagram renders as preformatted text:

    ```plantuml format="svg" classes="uml" alt="Client/Server" title="Client/Server"
    class Foo
    ```

This one renders fine:

    ```plantuml format="svg" classes="uml" alt="Client Server" title="Client Server"
    class Foo
    ```

(This is using the PlantUML service for rendering.)

**Comment by mikitex70** [comment]
Fixed, do a `pip install plantuml_markdown` to pull version `3.1.4`.
Thanks for reporting.
