### ISSUE TITLE
config: missing parameter for include path

### ISSUE THREAD

**Issue by christo-ph** [mikitex70/plantuml-markdown#37]
I cannot find the `plantuml.include.path` parameter with this plugin.

Found here: https://forum.plantuml.net/1553/how-to-pass-a-search-path-for-include-files

Example call:
`java -Dplantuml.include.path="c:/mydir" -jar plantuml.jar atest1.txt`

**Comment by mikitex70** [comment]
I'm not sure to add a new configuration option to the `plantuml_markdown` extension is a good idea.
First, added one option someone can ask for adding other options, which maybe very specific.
Second, there are workarounds:
1. modify the `plantuml` script (see README.md) which is called by this plugin adding the required options (`-Dplantuml.include.path=some/custom/path` in this case), or the use of an environment variable
1. exporting the variable `_JAVA_OPTIONS` with the required options before running `markdown_py`:
    * `export _JAVA_OPTIONS='-Dplantuml.include.path=some/custom/path'` in Linux
    * `set _JAVA_OPTIONS=-Dplantuml.include.path=C:/some/custom/path` for Windows

With both methods would be easy add any custom option, such memory tuning.

If there is some specific use case for which an extension configuration option may be better let me known, I would implement it.

**Comment by mikitex70** [comment]
Closing this issue as seems the workaround can be useful.
I cannot inject Java properties through the plugin as it would break compatibility with the `plantuml` system command.
Thanks for reporting this issue, it may be useful to others.
