### ISSUE TITLE
plugin does not work with pymdownx.snippet

### ISSUE THREAD

**Issue by Addisco** [mikitex70/plantuml-markdown#38]
Due to the high priority of `100` of the plantuml extensions it does not work with the [snippets extension](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/) which registers with a priority of `32`. 

Currently the plantuml extension processes the Snippets Notation as plantuml within fenced code blocks, instead of having snippets first be replaced. 

e.g. 
~~~
```plantuml
--8<-- "my-plantuml.puml"
```
~~~

will render as

![plantuml](https://www.plantuml.com/plantuml/png/0/qzMriD7LLL3AhTGjo4dCAodDpT4h019A0000 "plantuml")

**Comment by mikitex70** [comment]
Maybe a fine tuning of the `plantuml_markdown` extension may be desiderable in many other cases, but why not use the `!include` macro of PlantUML?
See #37 for an example of configuring the include search path used by PlantUML.

**Comment by Addisco** [comment]
That'll work, too! Thank a lot for the hint!

**Comment by mikitex70** [comment]
Release version 3.2.1 of the plugin.
Changed plugin priority so it works out-of-the-box with the snippets plugin and, maybe, others.
Version 3.2.1 has ha `priority` configuration property which can be used to change the plugin priority to the desired level in case of conflicts.
Closing this issue as seems to be resolved.
Thanks for reporting this issue.
