### ISSUE TITLE
PlantUML JSON support

### ISSUE THREAD

**Issue by ldeluigi** [mikitex70/plantuml-markdown#54]
Please add support for json: https://plantuml.com/json

Maybe with
::json::

::end-json::

And

````
```plantjson
{
...
}
```
````

**Comment by mikitex70** [comment]
Hi @ldeluigi,
have you tried to use `@startjson` and `@endjson` in the code diagram, inside the fence?
It should work...

**Comment by mikitex70** [comment]
Without includes it works.
Example:
````markdown
# Title

```uml
@startjson
{
   "fruit":"Apple",
   "size":"Large",
   "color":"Red"
}
@endjson
```
````
Output:
![immagine](https://user-images.githubusercontent.com/2070527/119018702-a89f9700-b99c-11eb-8081-676bb5afe2cf.png)

**Comment by mikitex70** [comment]
It works with include also.
Example (test.md):
````markdown
# Title

```uml
@startjson
!include value.json
@endjson
```
````
value.json:
```json
{
   "fruit":"Apple",
   "size":"Large",
   "color":"Red"
}
```
output:
![immagine](https://user-images.githubusercontent.com/2070527/119019441-80fcfe80-b99d-11eb-80b1-ddd8831b0473.png)

**Comment by ldeluigi** [comment]
Curious: I'll try more use cases and I will let you know

**Comment by ldeluigi** [comment]
![image](https://user-images.githubusercontent.com/44567586/119021952-52345780-b9a0-11eb-9794-3aae571e5801.png)

**Comment by ldeluigi** [comment]
I didnt' put the !include inside two @startjson @endjson

**Comment by ldeluigi** [comment]
Ok now it works! Well thanks for the support
