### ISSUE TITLE
UUID in requirements.txt

### ISSUE THREAD

**Issue by borystua** [mikitex70/plantuml-markdown#59]
Why would you want to install it? It is part of the cpython - https://docs.python.org/3.5/library/uuid.html
And, your script is most certainly using the system uuid instead of the "installed" one
https://pypi.org/project/uuid/#history
Installed one was last updated in 2006 and causes errors

**Comment by borystua** [comment]
#60

**Comment by mikitex70** [comment]
Fixed by your pull request #60.
Thanks for your contribution.
