### ISSUE TITLE
Provide option to generate "Error images" on bad plantuml syntax instead of raising an error

### ISSUE THREAD

**Issue by goldsam** [mikitex70/plantuml-markdown#61]
# Summary

I propose an mode of operation where syntax errors (or any plantuml errors) are encoded within the generated image itself.

# Context

I am trying to use plantuml-markdown as an mkdocs plugin while performing live-reload editing via `mkdocs serve`. The implementation of `mkdocs serve` aborts on any raised python error (`PlantUMLHTTPError` in my case). This forces the user to restart the mkdocs server resulting in a very unpleasant user experience.

While you could argue this is a problem with mkdocs and not this plugin, I would counter that exposing errors message in place of the generated image would produce a very nice user experience for many use cases. In documents containing many diagrams, this would allow the user to receive inline error feedback instead if out-of-band feedback via error message and stack trace.

As another example use case, consider a CI/CD development pipeline where it is undesirable to fail an entire documentation build due to one line of bad syntax. 

The approach I am suggesting is used by [vscode-markdown-preview-enhanced](https://github.com/shd101wyy/vscode-markdown-preview-enhanced) and produces a very nice user experience. Below is an example screenshot:

![Example inline plantuml error!](https://i.stack.imgur.com/NjDae.png "Example inline plantuml error")

**Comment by mikitex70** [comment]
Hi @goldsam, the behavior should already be that.
Example diagram with bad syntax:
````
```uml

component "a" #0000a0 as aaa

```
````

Rendered page:
![immagine](https://user-images.githubusercontent.com/2070527/155668241-03ba4a3b-a41e-4610-952d-3522ae048c6f.png)

and in the `mkdocs` logs:
```
INFO     -  [07:48:02] Detected file changes
INFO     -  Building documentation...
Error in "uml" directive: b'ERROR\n1\nSyntax Error?\nSome diagram description contains errors\n'
INFO     -  [07:48:19] Reloading browsers
INFO     -  [07:48:19] Browser connected: http://localhost:8000/
```
The `mkdocs` does not restart, it simply detects page changes, logs an error and continues to run.

Can you give me more details to be able to reproduce your issue? What mkdocs and plantuml-markdown plugin version are you using? Can you attach a simple diagram with an error so I can do some test?

**Comment by goldsam** [comment]
I'm using the following versions:

* Python: 3.9
* MkDocs:1.2.3
* plantuml-markdown: 3.5.1

You can reproduce the issue using the actual [container project i'm working on](https://github.com/goldsam/mkdocs). For your convenience, the whole thing can be cloned, built and run using:

```bash
git clone https://github.com/goldsam/mkdocs.git goldsam-mkdocs-mre
cd goldsam-mkdocs-mre
dos2unix resources/entrypoint.sh
docker build . -t mkdocs
MSYS_NO_PATHCONV=1 docker run --rm -v $(pwd)/demo-project:/docs -p 8000:8000 mkdocs serve
```
Once the mkdocs server is up, try to save an invalid change to `demo-project\docs\index.md`. For me, mkdocs immediately crashes with a stack trace.

**Comment by mikitex70** [comment]
Hi @goldsam, I was able to reproduce your issue and to fix it.
The problem was in the `plantuml` package, which raises an exception if the remote server respond with an HTTP 400.
I was able to do a workaround and now it should work as expected; try version `3.5.2`.
Thanks for reporting it.

**Comment by goldsam** [comment]
Thank you so much @mikitex70! 😊
