### ISSUE TITLE
License in setup.py is different from LICENSE file

### ISSUE THREAD

**Issue by nikstur** [mikitex70/plantuml-markdown#64]
setup.py specifies that plantuml-markdown is licensed under an MIT license. The actual LICENSE file hower, looks like the BSD 2-Clause license.

**Comment by mikitex70** [comment]
This escaped me. I will fix it as soon as possible.

**Comment by mikitex70** [comment]
Fixed the incoherence between licenses.
I haven't released a new package, the license on `pypi` will be fixed at the next release.
