### ISSUE TITLE
Config value: 'markdown_extensions'. Error: extendMarkdown() missing 1 required positional argument: 'md_globals'

### ISSUE THREAD

**Issue by mriedem** [mikitex70/plantuml-markdown#67]
The [3.4 release of Markdown dropped the `md_globals` kwarg](https://github.com/Python-Markdown/markdown/blob/master/docs/change_log/release-3.4.md) used here:

https://github.com/mikitex70/plantuml-markdown/blob/e264c85c738ff4390f412b2dff488f717025f9c3/plantuml_markdown.py#L349

Which results in an error.

We're using plantuml_markdown-3.5.3.

**Comment by mriedem** [comment]
Here was the deprecation notice: https://github.com/Python-Markdown/markdown/blob/a11431539d08e14b0bd821ceb101fa59d6a74c8a/docs/change_log/release-3.0.md#md_globals-keyword-deprecated-from-extension-api

**Comment by oprypin** [comment]
Could you include this solution into a new release? Otherwise this problem will keep having new occurrences for people

**Comment by mikitex70** [comment]
Released version `3.6.0` with this fix and some other enhancement.
