### ISSUE TITLE
python-plantuml as an optional dependency

### ISSUE THREAD

**Issue by nikstur** [mikitex70/plantuml-markdown#70]
@mikitex70 would you be willing for python-plantuml to be an optional depdency? You only need it if you want to render the diagrams on a server. As far as I can tell, if you want to render locally you don't need python-plantuml at all.

**Comment by mikitex70** [comment]
Hi @nikstur, from version `3.6.1` (just released) the `plantuml` dependency is completely removed.

**Comment by nikstur** [comment]
Oh perfect, that's a good change, thank you!
