### ISSUE TITLE
no file context for "WARNING in "uml" directive: remote server has returned error 400"

### ISSUE THREAD

**Issue by anb0s** [mikitex70/plantuml-markdown#75]
during investigation of #74 or some other rendering issues with Kroki instance (includes PlantUML server) i'm facing issue like
`WARNING in "uml" directive: remote server has returned error 400` but there is no context about the file and it's difficult (not possible) to find the markdown file that has the issue. 

Fixing the version to `3.4.3` shows callstack with previous exception message:

```
ERROR    -  Error reading page 'Guidance/API/20_OIE_Usage_Experience.md': 'PlantUMLHTTPError' object has no attribute 'message'
Traceback (most recent call last):
...
  File "/usr/local/lib/python3.9/site-packages/markdown/core.py", line 261, in convert
    self.lines = prep.run(self.lines)
  File "/usr/local/lib/python3.9/site-packages/plantuml_markdown.py", line 124, in run
    text1, idx1 = self._replace_block(text[idx:])
  File "/usr/local/lib/python3.9/site-packages/plantuml_markdown.py", line 182, in _replace_block
    diagram = self._render_diagram(code, requested_format)
  File "/usr/local/lib/python3.9/site-packages/plantuml_markdown.py", line 252, in _render_diagram
    diagram = self._render_remote_uml_image(code, requested_format)
  File "/usr/local/lib/python3.9/site-packages/plantuml_markdown.py", line 281, in _render_remote_uml_image
    return PlantUML("%s/%s/" % (self.config['server'], img_format)).processes(plantuml_code)
  File "/usr/local/lib/python3.9/site-packages/plantuml.py", line 173, in processes
    raise PlantUMLHTTPError(response, content)
  File "/usr/local/lib/python3.9/site-packages/plantuml.py", line 56, in __init__
    if not self.message:
AttributeError: 'PlantUMLHTTPError' object has no attribute 'message'
```

It would be good to see the context like file-path (like it was in the exception) and if possible the line (we have many diagrams in one file) or may be snippet of PlantUML text to search.

Additionally the `WARNING` message does not break the mkdocs strict build like it is for other WARNNG messages -> may be should create another issue to investigate...

**Comment by mikitex70** [comment]
Kroki uses a different diagram encoding than PlantUML; sending plantuml-encoded diagrams to Kroki does not work.
The error arise from the `plantuml` Python package, which is not mine.
I can implement kroki diagram encoding so that it is compatible.
Give me some time...

**Comment by anb0s** [comment]
Just to show example in VSCode (that also uses the Kroki/plantuml endpoint) for such broken diagram (merge conflicts) i've faced, it shows error message returned from server with line number:

![image](https://user-images.githubusercontent.com/95811/193906193-ae4f03c4-b86d-4b9b-aa0a-94c0d3f07d61.png)

So it shows the bad line in the diagram sended to PlantUML at Kroki, it would be good to see the markdown file-name with line number of diagram and the error message returned from server.
