### ISSUE TITLE
plugin does not work with markdown.extensions.fenced_code

### ISSUE THREAD

**Issue by ghost** [mikitex70/plantuml-markdown#8]
fenced_code extension is removing gitlab block-style code markers before plantuml
is running.

**Comment by lu-zero** [comment]
the current python markdown seems to do something even worse if codehilite is enabled

**Comment by mikitex70** [comment]
The problem is in the `fenced_code` plugin, which parses text before every plugin.
In the `fenced_code plugin` there is cabled a workaround for the `codehilite plugin`; I'm trying to register the `plantuml` plugin before `fenced_code`, maybe with a _monkey patch_.

**Comment by lu-zero** [comment]
Yes, my local solution had been patching fenced code and call it a day :)

**Comment by q3aiml** [comment]
Here's how I fixed this: https://github.com/q3aiml/plantuml-markdown/commit/df3b0ada1c32aa92d1ae4668fae6bdd9b4c4456c. I haven't opened a PR because I only retained support for the github backtick style block syntax. The ::uml:: syntax could still work but the different opening and closing tags likely require a separate regex.

**Comment by mikitex70** [comment]
Thanks @q3aiml, I will study your changes and try to merge them in the existing code.

**Comment by mikitex70** [comment]
Hi @q3aiml, I've managed to merge your proprosed code.
I need to do other (small) changes (comment the code) but it should work.
I'm planning to write some test; in the meanwhile can you do some small run to see if all is working as expected?
Thanks again for you contribution.

**Comment by q3aiml** [comment]
:+1: looks good here. Both styles are working. Thanks so much for reviewing and doing all the work to make it mergeable

**Comment by mikitex70** [comment]
I'm working on, I'm writing some unit test to keep the code tested.
Be patient, I will try to fix it in this weekend.
What branch have you used, the `master` or the `develop` branch?

**Comment by q3aiml** [comment]
@seanhoughton do you have a small example? I have only done basic testing but it works if I take the develop branch and drop the example from the readme in a doc twice. It was also working with my documents but they are admittedly all fairly similar. Or maybe it depends on either the markdown config or version?

**Comment by mikitex70** [comment]
I've release the version v1.2.2 that should fix working with the fenced_code plugin.
I've also added some test, just to avoid regressions.

**Comment by mikitex70** [comment]
Released version 1.2.3, which fixes an issue with Python 2.7.
Now the plugin is tested with various versions of Python, from 2.7 to 3.6.
I hope this will reduce the possibility of regressions.
