### ISSUE TITLE
Make insecure config default a boolean instead of a string literal

### ISSUE THREAD

**Issue by rvdmei** [mikitex70/plantuml-markdown#86]
I'm using `plantuml-markdown` with a private root CA on the plantuml server. This is installed properly on the system and overridden with environment variables for `requests` library, even copied to the location that `certifi` package is using. 

With this setup I am still getting warnings from requests library that `certificate verification is strongly advised`.

After some checking I found that the parameters that `session.post` for the `verify` parameter should be a `boolean`, or location of a certificate bundle. The current default setting is a sting literal: https://github.com/mikitex70/plantuml-markdown/blob/e48b04918315d769d91b4714f111f3f90668c872/plantuml_markdown.py#L611

Can this be changed to a simple `False` instead of `"False"` or will that break other things?

**Comment by mikitex70** [comment]
Hi @rvdmei, sure the default can be a boolean. This does not prevent of setting the variable as a path to a certificate, so I think there are no side effects.
Give a couple of hours, I think I can release the fix this night.

**Comment by rvdmei** [comment]
Awesome. I would have created a PR myself, but my employment contract would make the change not mine to give 😕

**Comment by mikitex70** [comment]
Just released version 3.8.3, now the default is a boolean `False`.
Thanks for your suggestion.
