### ISSUE TITLE
Multiple images in 1 file: legal?

### ISSUE THREAD

**Issue by charleshope** [mikitex70/plantuml-markdown#9]
Do you support multiple different UML blocks in the same MD file? I was not able to successfully embed two, or to successfully use two pairs of {@startuml, @enduml} in one block, either. If this is supposed to be supported, I'll add examples.

Thanks!

**Comment by mikitex70** [comment]
The problem may be similar to #10. There is a bug, diagrams in single block (without an empty line inside) are not recognized correctly.
As a  proof try this markdown (note the blank lines):

`````
```plantuml format="png" classes="uml myDiagram" alt="My super diagram placeholder" title="My super diagram"
Bob->Alice : hello

```

```plantuml format="png" classes="uml myDiagram" alt="My super diagram placeholder" title="My super diagram"
Bob<-Alice : hello

```
`````

**Comment by charleshope** [comment]
Should that example work if the two blank lines are removed? It didn't, I got

  File "/Users/chope/.ghdocs/.venv/lib/python2.7/site-packages/markdown/extensions/plantuml.py", line 98, in run
    raise RuntimeError("UML block not closed")
RuntimeError: UML block not closed
Terminated: 15

**Comment by charleshope** [comment]
Bumping for my open question. Thanks!
