### ISSUE TITLE
Add JSON schema for plugin options

### ISSUE THREAD

**Issue by mschoettle** [mikitex70/plantuml-markdown#98]
Hi @mikitex70,

Would you consider including an `extension-schema.json` in this repo that describes the valid configuration options (https://github.com/mikitex70/plantuml-markdown#plugin-options)?

mkdocs-material includes a schema for mkdocs.yml which allows the editor to validate the YAML file against this schema (see: https://squidfunk.github.io/mkdocs-material/creating-your-site/#minimal-configuration).

This schema could be referenced by mkdocs-material: https://github.com/squidfunk/mkdocs-material/issues/7159

I started with a definition here for the options we use: https://github.com/mschoettle/mkdocs-material/blob/24212492df2fe995809f6a5bda8fdbed00fc7f64/docs/schema/extensions/plantuml_markdown.json

**Comment by mikitex70** [comment]
Ho @mschoettle, sorry for the delay but I was a bit busy.
I've committed to the master branch a schema file based on your work, which has all the options.
If referenced by the MkDocs schema it allow you to validate all the options of this plugin.
Let me known if there is any issue.

**Comment by mschoettle** [comment]
Thanks a lot @mikitex70!

Created a PR to have it referenced here: https://github.com/squidfunk/mkdocs-material/pull/7260
